### PR TITLE
Fix linter and tiny improvments

### PR DESCRIPTION
**Pull request by Jibec**
Hi, here are my patches.

I suggest AGPL for this repository, I understand this also impact your source code.

### CODE REVIEW

**Comment by alexAubin** [comment]
Thanks for the help :heart: 

Not sure what are the implications of the AGPL ?

Honestly that sounds good for yolomerging to me ;)

**Comment by Jibec** [comment]
Don't yolomerge :)

https://www.quora.com/What-is-the-difference-between-GPL-AGPL-and-LGPL-licenses

> Now that you understand what each one is what is the difference between each one. I have simplified the differences below:
> 
> * LGPL: you can link against and don't have to release source code as long as you don't modify the library itself
> * GPL: you have to release source code if you link against and distribute the binary, but don't if you just provide a service
> * AGPL: you have to allow the source to be downloaded even if you never distribute the binary but do provide a service

**Comment by Jaxom99** [comment]
@Jibec (nb: licence-noob here) : Do you reckon AGPL implies that *every* yunohost multi-user instance (I'm thinking "family and friends" instances...) will have to make their source code available ? 
Maybe a release by the main Yunohost organization (which is already happening) could be considered compliant with AGPL, provided we all install from this source (default behaviour of the yunohost services). I'm willing to learn more if you have relevant sources of information ;)

**Comment by Jibec** [comment]
Le 26 octobre 2017 14:43:47 GMT+02:00, Jaxom99 <notifications@github.com> a écrit :
>@Jibec (nb: licence-noob here) : Do you reckon AGPL implies that
>*every* yunohost multi-user instance (I'm thinking "family and friends"
>instances...) will have to make their source code available ? 
>Maybe a release by the main Yunohost organization (which is already
>happening) could be considered compliant with AGPL, provided we all
>install from this source (default behaviour of the yunohost services).
>I'm willing to learn more if you have relevant sources of information
>;)

Well, it's quite simple.

First, the service provider is the one running the server. I am the service provider for my personal server for my friends and family.

With agpl software, if my users ask for jt, I should provide the package source code, which is already on github. I don't worry about this.

They do not have any obligation when using the software with personal data as only the package is concerned by the license.
-- 
Jean-Baptiste Holcroft

**Comment by alexAubin** [comment]
Initiating yolomerging

**Pull request merged**
